# Generated by Django 4.2.13 on 2024-08-14 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_strategy_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
