# Generated by Django 4.2.13 on 2024-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_strategy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
