# Generated by Django 4.2.13 on 2024-09-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
