# Generated by Django 4.2.13 on 2024-09-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trade_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='sheetUrl',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brokers'),
        ),
    ]
